import Head from 'next/head';
import Navbar from '../pages/sections/Navbar';
import Footer from '../pages/sections/Footer';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { useSession } from 'next-auth/react';
import DashboardLinks from './DashboardLinks';

function Layout({ children, title }) {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>{title ? title + " - Presente" : "Presente"}</title>
        <meta name="Fatec - Guaratinguetá" content="Generated by create next app by Ariel Paixão e João Machado" />
        <meta charSet="UTF-8" />
        <meta name="Fatec - Guaratinguetá" content="Um site especializado para a receber a lista de chamada da turma do 6º ADS de 2023" />
        <meta
          name="description"
          content="Lista de presença dos alunos de Análise e Desenvolvimento de Sistemas do 6º 2023"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <ToastContainer position="top-center" limit={1} />

      <div className='flex min-h-screen flex-col justify-between'>
        <header id="Up" className='fixed z-50 h-fit w-[100%]'>
          <Navbar />
        </header>
        {session?.user.isTeacher && (
          <div className='fixed top-20 z-50'>
            <DashboardLinks />
          </div>
        )}
        <main className='container mx-auto mt-24 px-4 sm:px-0 md:px-10'>{children}</main>
        <Footer />
      </div>
    </>
  )
}

export default Layout;
